name: barberia-vuejs
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: lalona/barberia-tronco-vuejs
  name: barberia-tronco-vuejs
